services:
  api:
    profiles: ["build"]
    image: agrippa1994/divessi-log-importer:${TAG:-latest}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
