apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: {{ $.Values.app.image }}:{{ $.Values.app.version }}
          imagePullPolicy: {{ $.Values.app.imagePullPolicy }}
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/health
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: SESSION_SECRET
              value: {{ $.Values.app.env.SESSION_SECRET | quote }}
            - name: DATA_DIR
              value: /data
          ports:
            - containerPort: 3000
              name: app
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: app-data
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.app.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
  - name: app
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: {{ $.Values.app.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 3000
  tls:
  - hosts:
    - {{ $.Values.app.host }}
    secretName: tls